---
- name: Uninstall Features
  become_user: "{{ user['name'] }}"
  shell: "source /home/{{ user['name'] }}/.bash_profile; {{ fuse_client}} 'features:uninstall {{ item }}'"
  args:
      chdir: /home/{{ user['name'] }}
      executable: /bin/bash
  with_items: '{{ features }}'
  when: features is defined 

- name: Stop Bundles
  become_user: "{{ user['name'] }}"
  shell: "source /home/{{ user['name'] }}/.bash_profile; {{ fuse_client}} 'bundle:stop {{ item }}'"
  args:
      chdir: /home/{{ user['name'] }}
      executable: /bin/bash
  with_items: '{{ bundles }}'
  when: bundles is defined 

- name: Uninstall Bundles
  become_user: "{{ user['name'] }}"
  shell: "source /home/{{ user['name'] }}/.bash_profile; {{ fuse_client}} 'bundle:uninstall {{ item }}'"
  args:
      chdir: /home/{{ user['name'] }}
      executable: /bin/bash
  with_items: '{{ bundles }}'
  when: bundles is defined 
