---
- name: EAP DEV Deploy Bundles Playbook
  hosts: eap-dev
  # vars_files:
  #   - vars/eapassets.yml
  gather_facts: true
  # become: yes
  roles:
    - {
        role: eap-deploy,
        deploy_wars: 'yes'
      }