---
- name: Fuse Dev Deploy Bundles Playbook
  hosts: fuse-dev
  # vars_files:
  #   - vars/deploy.yml
  gather_facts: true
  # become: yes
  roles:
    - {
        role: fuse-deploy,
        esb_name: 'fuseesb',
        deploy_features: 'yes',
        deploy_bundles: 'yes',
        deploy_config: 'yes'
      }