---
- name: delete deployed file
  file:
    path: '{{ jdvhome }}/deployments/{{ item.split("/")[-1] }}.deployed'
    state: absent
    mode: 0755
  with_items: "{{ deploylist }}"
  when: deploylist is defined and
        (deploylist is defined and deploy_wars == 'yes')

- name: wait for undeploy to finish
  wait_for:
      path: '{{ jdvhome }}/deployments/{{ item.split("/")[-1] }}.undeployed'
      state: present
      msg: Timeout to undeploy {{ item }}
      timeout: 60
  with_items: "{{ deploylist }}"
  when: deploylist is defined and (deploylist|length > 0)